### ISSUE TITLE
setJobGrade

### ISSUE THREAD

**Issue by reserect** [BryceCanyonCounty/bcc-jobmenu#2]
[    script:vorp_core] SCRIPT ERROR: @vorp_core/server/old_api.lua:145: attempt to call a nil value (field 'setJobGrade')
[    script:vorp_core] > handler (@bcc_jobmenu/server/server.lua:5)

**Comment by DavFount** [comment]
I have a fully rewritten version of this I need to test to work with the new stuff vorp has added. I'll let you know once the testing is finalized and live for updates

**Comment by reserect** [comment]
Okay thank you very much.

**Comment by DavFount** [comment]
This has been updated and tested in the latest release!
